**STUDENT PLACEMENT READINESS ANALYSIS**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Student_Placement_Readiness_Analysis_Records_Final.csv')

**EXPLORING DATASET**

In [ ]:
#First 5 rows
df.head()

,1. Year of Study,2. Current CGPA,3. How many programming languages do you know?,4. How many hours do you practice coding per day?,5. How many academic or personal projects have you completed?,6. Have you completed any internships?,7. How many certifications have you completed?,8. How would you rate your communication skills?,9. How often do you practice aptitude questions?,10. Have you participated in any hackathons or coding competitions?,"11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?",12. Is your resume ready?,13. How confident are you in attending placement interviews?,14. Which skill do you think you need to improve the most?
0,2nd year,9.00,2,3 hours,0.0,No,0,1.0,Never,Yes,Never,No,4.0,Communication
1,3rd year,8.60,1,Less than 2 hours,0.0,No,1-2,3.0,Never,No,Occassionally,No,1.0,Coding
2,3rd year,8.49,3,Less than 2 hours,1.0,Yes,1-2,2.0,Daily,Yes,Daily,No,1.0,Coding
3,3rd year,8.23,3,Not practicing,2.0,No,3-5,1.0,Never,Yes,Never,No,1.0,Coding
4,3rd year,7.88,1,Not practicing,3.0,No,0,4.0,Occassionally,Yes,Never,No,3.0,Coding

In [ ]:
#Last 5 rows
df.tail()

,1. Year of Study,2. Current CGPA,3. How many programming languages do you know?,4. How many hours do you practice coding per day?,5. How many academic or personal projects have you completed?,6. Have you completed any internships?,7. How many certifications have you completed?,8. How would you rate your communication skills?,9. How often do you practice aptitude questions?,10. Have you participated in any hackathons or coding competitions?,"11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?",12. Is your resume ready?,13. How confident are you in attending placement interviews?,14. Which skill do you think you need to improve the most?
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns=df.columns.str.strip()

In [ ]:
#All Column names
df.columns

Index(['1. Year of Study', '2.  Current CGPA',
       '3. How many programming languages do you know?',
       '4. How many hours do you practice coding per day?',
       '5. How many academic or personal projects have you completed?',
       '6. Have you completed any internships?',
       '7. How many certifications have you completed?',
       '8. How would you rate your communication skills?',
       '9. How often do you practice aptitude questions?',
       '10. Have you participated in any hackathons or coding competitions?',
       '11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?',
       '12. Is your resume ready?',
       '13. How confident are you in attending placement interviews?',
       '14. Which skill do you think you need to improve the most?'],
      dtype='object')

In [ ]:
#No. of rows and columns
df.shape

(120, 14)

In [ ]:
#Datatype of all columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 14 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   1. Year of Study                                                                         103 non-null    object
 1   2.  Current CGPA                                                                         98 non-null     float64
 2   3. How many programming languages do you know?                                           103 non-null    object
 3   4. How many hours do you practice coding per day?                                        103 non-null    object
 4   5. How many academic or personal projects have you completed?                            103 non-null    float64
 5   6. Have you completed any internships?                                                   103 non-null    object
 6   7. How many certifications have you completed?                                           99 non-null     object
 7   8. How would you rate your communication skills?                                         103 non-null    float64
 8   9. How often do you practice aptitude questions?                                         103 non-null    object
 9   10. Have you participated in any hackathons or coding competitions?                      103 non-null    object
 10  11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?  103 non-null    object
 11  12. Is your resume ready?                                                                103 non-null    object
 12  13. How confident are you in attending placement interviews?                             103 non-null    float64
 13  14. Which skill do you think you need to improve the most?                               103 non-null    object
dtypes: float64(4), object(10)
memory usage: 13.3+ KB

In [ ]:
#Statistical summary for numeric columns
df.describe()

,2. Current CGPA,5. How many academic or personal projects have you completed?,8. How would you rate your communication skills?,13. How confident are you in attending placement interviews?
count,98.000000,103.000000,103.000000,103.000000
mean,8.561837,1.601942,4.533981,2.776699
std,0.532598,0.953218,1.453970,0.949014
min,7.000000,0.000000,1.000000,1.000000
25%,8.407500,1.000000,4.000000,2.000000
50%,8.660000,2.000000,5.000000,3.000000
75%,8.970000,2.000000,6.000000,3.000000
max,9.200000,3.000000,7.000000,5.000000

In [ ]:
#Unique values in each column
df.nunique()

1. Year of Study                                                                            3
2.  Current CGPA                                                                           24
3. How many programming languages do you know?                                              4
4. How many hours do you practice coding per day?                                           3
5. How many academic or personal projects have you completed?                               4
6. Have you completed any internships?                                                      2
7. How many certifications have you completed?                                              4
8. How would you rate your communication skills?                                            7
9. How often do you practice aptitude questions?                                            4
10. Have you participated in any hackathons or coding competitions?                         2
11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?     4
12. Is your resume ready?                                                                   2
13. How confident are you in attending placement interviews?                                5
14. Which skill do you think you need to improve the most?                                  3
dtype: int64

In [ ]:
#Statistical summary for categorical columns
df.describe(include="object")

,1. Year of Study,3. How many programming languages do you know?,4. How many hours do you practice coding per day?,6. Have you completed any internships?,7. How many certifications have you completed?,9. How often do you practice aptitude questions?,10. Have you participated in any hackathons or coding competitions?,"11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?",12. Is your resume ready?,14. Which skill do you think you need to improve the most?
count,103,103,103,103,99,103,103,103,103,103
unique,3,4,3,2,4,4,2,4,2,3
top,3rd year,3,Less than 2 hours,No,1-2,Occassionally,Yes,Occassionally,No,Coding
freq,65,47,53,52,46,47,92,47,74,71

**DATA CLEANING**

In [ ]:
#Checking Null values
df.isnull().sum()

1. Year of Study                                                                           17
2.  Current CGPA                                                                           22
3. How many programming languages do you know?                                             17
4. How many hours do you practice coding per day?                                          17
5. How many academic or personal projects have you completed?                              17
6. Have you completed any internships?                                                     17
7. How many certifications have you completed?                                             21
8. How would you rate your communication skills?                                           17
9. How often do you practice aptitude questions?                                           17
10. Have you participated in any hackathons or coding competitions?                        17
11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?    17
12. Is your resume ready?                                                                  17
13. How confident are you in attending placement interviews?                               17
14. Which skill do you think you need to improve the most?                                 17
dtype: int64

In [ ]:
# Fill missing values in numerical columns using mean
df['2.  Current CGPA']=df['2.  Current CGPA'].fillna(df['2.  Current CGPA'].mean())

In [ ]:
df['4. How many hours do you practice coding per day?']=df['4. How many hours do you practice coding per day?'].fillna(df['4. How many hours do you practice coding per day?'].mode()[0])

In [ ]:
df['7. How many certifications have you completed?'] = df['7. How many certifications have you completed?'].fillna(df['7. How many certifications have you completed?'].mode()[0])

In [ ]:
df['13. How confident are you in attending placement interviews?'] = df['13. How confident are you in attending placement interviews?'].fillna(df['13. How confident are you in attending placement interviews?'].mean())

In [ ]:
df.isnull().sum()

1. Year of Study                                                                           17
2.  Current CGPA                                                                            0
3. How many programming languages do you know?                                             17
4. How many hours do you practice coding per day?                                           0
5. How many academic or personal projects have you completed?                              17
6. Have you completed any internships?                                                     17
7. How many certifications have you completed?                                              0
8. How would you rate your communication skills?                                           17
9. How often do you practice aptitude questions?                                           17
10. Have you participated in any hackathons or coding competitions?                        17
11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?    17
12. Is your resume ready?                                                                  17
13. How confident are you in attending placement interviews?                                0
14. Which skill do you think you need to improve the most?                                 17
dtype: int64

In [ ]:
df['1. Year of Study']=df['1. Year of Study'].fillna(df['1. Year of Study'].mode()[0])

In [ ]:
df['3. How many programming languages do you know?'] = df['3. How many programming languages do you know?'].fillna(df['3. How many programming languages do you know?'].mode()[0])

In [ ]:
df['5. How many academic or personal projects have you completed?'] = df['5. How many academic or personal projects have you completed?'].fillna(df['5. How many academic or personal projects have you completed?'].mode()[0])

In [ ]:
df['6. Have you completed any internships?'] = df['6. Have you completed any internships?'].fillna(df['6. Have you completed any internships?'].mode()[0])

In [ ]:
df['8. How would you rate your communication skills?'] = df['8. How would you rate your communication skills?'].fillna(df['8. How would you rate your communication skills?'].mode()[0])

In [ ]:
df['9. How often do you practice aptitude questions?'] = df['9. How often do you practice aptitude questions?'].fillna(df['9. How often do you practice aptitude questions?'].mode()[0])

In [ ]:
df['10. Have you participated in any hackathons or coding competitions?'] = df['10. Have you participated in any hackathons or coding competitions?'].fillna(df['10. Have you participated in any hackathons or coding competitions?'].mode()[0])

In [ ]:
df['11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?'] = df['11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?'].fillna(df['11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?'].mode()[0])

In [ ]:
df['12. Is your resume ready?'] = df['12. Is your resume ready?'].fillna(df['12. Is your resume ready?'].mode()[0])

In [ ]:
df['14. Which skill do you think you need to improve the most?'] = df['14. Which skill do you think you need to improve the most?'].fillna(df['14. Which skill do you think you need to improve the most?'].mode()[0])

In [ ]:
df.isnull().sum()

1. Year of Study                                                                           0
2.  Current CGPA                                                                           0
3. How many programming languages do you know?                                             0
4. How many hours do you practice coding per day?                                          0
5. How many academic or personal projects have you completed?                              0
6. Have you completed any internships?                                                     0
7. How many certifications have you completed?                                             0
8. How would you rate your communication skills?                                           0
9. How often do you practice aptitude questions?                                           0
10. Have you participated in any hackathons or coding competitions?                        0
11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?    0
12. Is your resume ready?                                                                  0
13. How confident are you in attending placement interviews?                               0
14. Which skill do you think you need to improve the most?                                 0
dtype: int64

In [ ]:
#Checking duplicate values
df.duplicated().sum()

np.int64(34)

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

**EPLORATORY DATA ANALYSIS(EDA)**

In [ ]:
df.head()

,1. Year of Study,2. Current CGPA,3. How many programming languages do you know?,4. How many hours do you practice coding per day?,5. How many academic or personal projects have you completed?,6. Have you completed any internships?,7. How many certifications have you completed?,8. How would you rate your communication skills?,9. How often do you practice aptitude questions?,10. Have you participated in any hackathons or coding competitions?,"11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?",12. Is your resume ready?,13. How confident are you in attending placement interviews?,14. Which skill do you think you need to improve the most?
0,2nd year,9.00,2,3 hours,0.0,No,0,1.0,Never,Yes,Never,No,4.0,Communication
1,3rd year,8.60,1,Less than 2 hours,0.0,No,1-2,3.0,Never,No,Occassionally,No,1.0,Coding
2,3rd year,8.49,3,Less than 2 hours,1.0,Yes,1-2,2.0,Daily,Yes,Daily,No,1.0,Coding
3,3rd year,8.23,3,Not practicing,2.0,No,3-5,1.0,Never,Yes,Never,No,1.0,Coding
4,3rd year,7.88,1,Not practicing,3.0,No,0,4.0,Occassionally,Yes,Never,No,3.0,Coding

In [ ]:
df.shape

(86, 14)

In [ ]:
df.describe()

,2. Current CGPA,5. How many academic or personal projects have you completed?,8. How would you rate your communication skills?,13. How confident are you in attending placement interviews?
count,86.000000,86.000000,86.000000,86.000000
mean,8.545150,1.639535,4.569767,2.748024
std,0.551184,0.906354,1.418704,0.956029
min,7.000000,0.000000,1.000000,1.000000
25%,8.430000,1.250000,4.000000,2.000000
50%,8.600000,2.000000,5.000000,3.000000
75%,8.970000,2.000000,6.000000,3.000000
max,9.200000,3.000000,7.000000,5.000000

In [ ]:
df['1. Year of Study'].value_counts()

1. Year of Study
3rd year    52
4th year    31
2nd year     3
Name: count, dtype: int64

In [ ]:
# Internship completed students

df['6. Have you completed any internships?'].value_counts()

6. Have you completed any internships?
No     43
Yes    43
Name: count, dtype: int64

In [ ]:
# Certification analysis

df['7. How many certifications have you completed?'].value_counts()

7. How many certifications have you completed?
1-2            38
0              23
3-5            13
More than 5    12
Name: count, dtype: int64

In [ ]:
# Resume readiness analysis

df['12. Is your resume ready?'].value_counts()

12. Is your resume ready?
No     61
Yes    25
Name: count, dtype: int64

In [ ]:
# Interview confidence analysis

df['13. How confident are you in attending placement interviews?'].value_counts()

13. How confident are you in attending placement interviews?
3.000000    39
2.000000    21
4.000000    10
1.000000     9
5.000000     4
2.776699     3
Name: count, dtype: int64

In [ ]:
# Programming language knowledge analysis

df['3. How many programming languages do you know?'].value_counts()

3. How many programming languages do you know?
3              40
More than 3    20
1              14
2              12
Name: count, dtype: int64

**VISUALIZATIONS**

In [ ]:
import plotly.express as px

In [ ]:
year_count = df['1. Year of Study'].value_counts()

fig = px.bar(
    x=year_count.index,
    y=year_count.values,
    title="Year of Study Distribution"
)

fig.show()

In [ ]:
fig = px.histogram(
    df,
    x='2.  Current CGPA',
    title="Distribution of Student CGPA"
)

fig.show()

In [ ]:
language_count = df['3. How many programming languages do you know?'].value_counts()

fig = px.bar(
    x=language_count.index,
    y=language_count.values,
    title="Programming Languages Known by Students"
)

fig.show()

In [ ]:
coding_hours = df['4. How many hours do you practice coding per day?'].value_counts()

fig = px.pie(
    values=coding_hours.values,
    names=coding_hours.index,
    title="Daily Coding Practice Hours"
)

fig.show()

In [ ]:
fig = px.box(
    df,
    y='5. How many academic or personal projects have you completed?',
    title="Projects Completed Distribution"
)

fig.show()

In [ ]:
internship = df['6. Have you completed any internships?'].value_counts()

fig = px.pie(
    values=internship.values,
    names=internship.index,
    title="Internship Completion Status"
)

fig.show()

In [ ]:
certification = df['7. How many certifications have you completed?'].value_counts()

fig = px.bar(
    x=certification.index,
    y=certification.values,
    title="Certification Completion Analysis"
)

fig.show()

In [ ]:
fig = px.histogram(
    df,
    x='8. How would you rate your communication skills?',
    title="Communication Skills Rating Distribution"
)

fig.show()

In [ ]:
aptitude = df['9. How often do you practice aptitude questions?'].value_counts()

fig = px.pie(
    values=aptitude.values,
    names=aptitude.index,
    title="Aptitude Practice Frequency"
)

fig.show()

In [ ]:
hackathon = df['10. Have you participated in any hackathons or coding competitions?'].value_counts()

fig = px.pie(
    values=hackathon.values,
    names=hackathon.index,
    title="Hackathon Participation"
)

fig.show()

In [ ]:
platform = df['11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?'].value_counts()

fig = px.bar(
    x=platform.index,
    y=platform.values,
    title="Coding Platform Practice"
)

fig.show()

In [ ]:
resume = df['12. Is your resume ready?'].value_counts()

fig = px.pie(
    values=resume.values,
    names=resume.index,
    title="Resume Readiness Status"
)

fig.show()

In [ ]:
fig = px.scatter(
    df,
    x='2.  Current CGPA',
    y='13. How confident are you in attending placement interviews?',
    title="CGPA vs Placement Confidence"
)

fig.show()

In [ ]:
skill = df['14. Which skill do you think you need to improve the most?'].value_counts()

fig = px.bar(
    x=skill.values,
    y=skill.index,
    orientation='h',
    title="Skills Students Need to Improve"
)

fig.show()

In [ ]:
fig = px.scatter(
    df,
    x="2.  Current CGPA",
    y="13. How confident are you in attending placement interviews?",
    size="5. How many academic or personal projects have you completed?",
    color="6. Have you completed any internships?",
    hover_name="1. Year of Study",
    title="CGPA vs Placement Confidence Analysis"
)

fig.show()

In [ ]:
fig = px.scatter(
    df,
    x="4. How many hours do you practice coding per day?",
    y="13. How confident are you in attending placement interviews?",
    color="6. Have you completed any internships?",
    title="Coding Practice vs Placement Confidence"
)

fig.show()

In [ ]:
year_data=df.groupby("1. Year of Study")["2.  Current CGPA"].mean()

fig=px.line(
    x=year_data.index,
    y=year_data.values,
    title="Average CGPA by Year of Study"
)

fig.show()

In [ ]:
intern=df.groupby("6. Have you completed any internships?")["13. How confident are you in attending placement interviews?"].mean()

fig=px.bar(
    x=intern.index,
    y=intern.values,
    title="Internship Impact on Placement Confidence"
)

fig.show()

In [ ]:
fig=px.box(
    df,
    x="5. How many academic or personal projects have you completed?",
    y="2.  Current CGPA",
    title="Projects Completed vs CGPA"
)

fig.show()

In [ ]:
fig=px.box(
    df,
    x="12. Is your resume ready?",
    y="2.  Current CGPA",
    title="Resume Readiness vs CGPA"
)

fig.show()

In [ ]:
skill=df["14. Which skill do you think you need to improve the most?"].value_counts()

fig=px.line(
    x=skill.index,
    y=skill.values,
    title="Skills Improvement Trend"
)

fig.show()

In [ ]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=("CGPA Distribution",
                    "Coding Practice Hours",
                    "Internship Status",
                    "Certifications"),
    specs=[[{}, {}],
           [{'type':'domain'}, {}]]
)

# Histogram for CGPA
fig.add_trace(
    go.Histogram(
        x=df['2.  Current CGPA']
    ),
    row=1,col=1
)

# Bar chart for coding hours
coding=df["4. How many hours do you practice coding per day?"].value_counts()

fig.add_trace(
    go.Bar(
        x=coding.index,
        y=coding.values
    ),
    row=1,col=2
)

# Pie chart for internships
intern=df["6. Have you completed any internships?"].value_counts()

fig.add_trace(
    go.Pie(
        labels=intern.index,
        values=intern.values
    ),
    row=2,col=1
)


# Bar chart for certifications
cert=df["7. How many certifications have you completed?"].value_counts()

fig.add_trace(
    go.Bar(
        x=cert.index,
        y=cert.values
    ),
    row=2,col=2
)


fig.update_layout(
    height=700,
    title="Student Skills Insights Dashboard"
)

fig.show()

In [ ]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=("Communication Skills",
                    "Aptitude Practice",
                    "Coding Platforms Usage",
                    "Interview Confidence")
)


# Histogram for communication skills

fig.add_trace(
    go.Histogram(
        x=df["8. How would you rate your communication skills?"]
    ),
    row=1,col=1
)


# Bar chart aptitude practice

apt=df["9. How often do you practice aptitude questions?"].value_counts()

fig.add_trace(
    go.Bar(
        x=apt.index,
        y=apt.values
    ),
    row=1,col=2
)


# Bar chart coding platforms

platform=df["11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?"].value_counts()

fig.add_trace(
    go.Bar(
        x=platform.index,
        y=platform.values
    ),
    row=2,col=1
)


# Histogram interview confidence

fig.add_trace(
    go.Histogram(
        x=df["13. How confident are you in attending placement interviews?"]
    ),
    row=2,col=2
)


fig.update_layout(
    height=700,
    title="Placement Readiness Dashboard"
)

fig.show()

**INSIGHTS**

**Academic Performance Analysis**

*   Most students maintain a good CGPA range, showing strong academic performance among the respondents.
*   Higher CGPA students may have better readiness for placement opportunities.


**Programming Language Knowledge**

*   Many students know at least 1-3 programming languages.
*  Improving programming skills can increase technical confidence.


**Coding Practice Analysis**

*   A large number of students spend less time practicing coding regularly.
*   Consistent coding practice is required to improve problem-solving skills.


**Project Experience**

*   Students with more academic or personal projects have better practical exposure.
*   Building real-world projects improves placement preparation.


**Internship Analysis**

*   Some students have completed internships, while many are still lacking industry experience.
* More internship participation can improve professional skills.  


**Certification Analysis**

*   Most students completed a few certifications.
*   Certifications help students learn new technologies and strengthen resumes.



**Communication Skills Analysis**

*   Students with higher communication ratings are more confident about placement interviews.
*   Soft skills improvement is important along with technical knowledge.



**Aptitude Practice Analysis**


*   Regular aptitude practice is followed by fewer students.
*   Increasing aptitude preparation can improve placement test performance.



**Coding Platform Usage**

*   Students who regularly use platforms like HackerRank, LeetCode, or CodeChef have better coding practice habits.  


**Placement Confidence Analysis**

*   Interview confidence depends on multiple factors like coding skills, projects, communication, and preparation.


**Overall Conclusion**

The analysis shows that students are improving their technical skills through programming, projects, and certifications. However, regular coding practice, internships, aptitude preparation, and interview skills need more focus to increase placement readiness.

In [70]:
# Save cleaned dataset

df.to_csv("Cleaned_Student_Placement_Readiness_Data.csv", index=False)