**STUDENT PLACEMENT READINESS ANALYSIS**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df=pd.read_csv('/content/drive/MyDrive/Student_Placement_Readiness_Analysis_Records_Final.csv')

**EXPLORING DATASET**

In [5]:
#First 5 rows
df.head()

,1. Year of Study,2. Current CGPA,3. How many programming languages do you know?,4. How many hours do you practice coding per day?,5. How many academic or personal projects have you completed?,6. Have you completed any internships?,7. How many certifications have you completed?,8. How would you rate your communication skills?,9. How often do you practice aptitude questions?,10. Have you participated in any hackathons or coding competitions?,"11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?",12. Is your resume ready?,13. How confident are you in attending placement interviews?,14. Which skill do you think you need to improve the most?
0,2nd year,9.00,2,3 hours,0.0,No,0,1.0,Never,Yes,Never,No,4.0,Communication
1,3rd year,8.60,1,Less than 2 hours,0.0,No,1-2,3.0,Never,No,Occassionally,No,1.0,Coding
2,3rd year,8.49,3,Less than 2 hours,1.0,Yes,1-2,2.0,Daily,Yes,Daily,No,1.0,Coding
3,3rd year,8.23,3,Not practicing,2.0,No,3-5,1.0,Never,Yes,Never,No,1.0,Coding
4,3rd year,7.88,1,Not practicing,3.0,No,0,4.0,Occassionally,Yes,Never,No,3.0,Coding

In [6]:
#Last 5 rows
df.tail()

,1. Year of Study,2. Current CGPA,3. How many programming languages do you know?,4. How many hours do you practice coding per day?,5. How many academic or personal projects have you completed?,6. Have you completed any internships?,7. How many certifications have you completed?,8. How would you rate your communication skills?,9. How often do you practice aptitude questions?,10. Have you participated in any hackathons or coding competitions?,"11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?",12. Is your resume ready?,13. How confident are you in attending placement interviews?,14. Which skill do you think you need to improve the most?
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.columns=df.columns.str.strip()

In [8]:
#All Column names
df.columns

Index(['1. Year of Study', '2.  Current CGPA',
       '3. How many programming languages do you know?',
       '4. How many hours do you practice coding per day?',
       '5. How many academic or personal projects have you completed?',
       '6. Have you completed any internships?',
       '7. How many certifications have you completed?',
       '8. How would you rate your communication skills?',
       '9. How often do you practice aptitude questions?',
       '10. Have you participated in any hackathons or coding competitions?',
       '11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?',
       '12. Is your resume ready?',
       '13. How confident are you in attending placement interviews?',
       '14. Which skill do you think you need to improve the most?'],
      dtype='object')

In [9]:
#No. of rows and columns
df.shape

(120, 14)

In [10]:
#Datatype of all columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 14 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   1. Year of Study                                                                         103 non-null    object
 1   2.  Current CGPA                                                                         98 non-null     float64
 2   3. How many programming languages do you know?                                           103 non-null    object
 3   4. How many hours do you practice coding per day?                                        103 non-null    object
 4   5. How many academic or personal projects have you completed?                            103 non-null    float64
 5   6. Have you completed any internships?                                                   103 non-null    object
 6   7. How many certifications have you completed?                                           99 non-null     object
 7   8. How would you rate your communication skills?                                         103 non-null    float64
 8   9. How often do you practice aptitude questions?                                         103 non-null    object
 9   10. Have you participated in any hackathons or coding competitions?                      103 non-null    object
 10  11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?  103 non-null    object
 11  12. Is your resume ready?                                                                103 non-null    object
 12  13. How confident are you in attending placement interviews?                             103 non-null    float64
 13  14. Which skill do you think you need to improve the most?                               103 non-null    object
dtypes: float64(4), object(10)
memory usage: 13.3+ KB

In [11]:
#Statistical summary for numeric columns
df.describe()

,2. Current CGPA,5. How many academic or personal projects have you completed?,8. How would you rate your communication skills?,13. How confident are you in attending placement interviews?
count,98.000000,103.000000,103.000000,103.000000
mean,8.561837,1.601942,4.533981,2.776699
std,0.532598,0.953218,1.453970,0.949014
min,7.000000,0.000000,1.000000,1.000000
25%,8.407500,1.000000,4.000000,2.000000
50%,8.660000,2.000000,5.000000,3.000000
75%,8.970000,2.000000,6.000000,3.000000
max,9.200000,3.000000,7.000000,5.000000

In [12]:
#Unique values in each column
df.nunique()

1. Year of Study                                                                            3
2.  Current CGPA                                                                           24
3. How many programming languages do you know?                                              4
4. How many hours do you practice coding per day?                                           3
5. How many academic or personal projects have you completed?                               4
6. Have you completed any internships?                                                      2
7. How many certifications have you completed?                                              4
8. How would you rate your communication skills?                                            7
9. How often do you practice aptitude questions?                                            4
10. Have you participated in any hackathons or coding competitions?                         2
11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?     4
12. Is your resume ready?                                                                   2
13. How confident are you in attending placement interviews?                                5
14. Which skill do you think you need to improve the most?                                  3
dtype: int64

In [13]:
#Statistical summary for categorical columns
df.describe(include="object")

,1. Year of Study,3. How many programming languages do you know?,4. How many hours do you practice coding per day?,6. Have you completed any internships?,7. How many certifications have you completed?,9. How often do you practice aptitude questions?,10. Have you participated in any hackathons or coding competitions?,"11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?",12. Is your resume ready?,14. Which skill do you think you need to improve the most?
count,103,103,103,103,99,103,103,103,103,103
unique,3,4,3,2,4,4,2,4,2,3
top,3rd year,3,Less than 2 hours,No,1-2,Occassionally,Yes,Occassionally,No,Coding
freq,65,47,53,52,46,47,92,47,74,71

**DATA CLEANING**

In [14]:
#Checking Null values
df.isnull().sum()

1. Year of Study                                                                           17
2.  Current CGPA                                                                           22
3. How many programming languages do you know?                                             17
4. How many hours do you practice coding per day?                                          17
5. How many academic or personal projects have you completed?                              17
6. Have you completed any internships?                                                     17
7. How many certifications have you completed?                                             21
8. How would you rate your communication skills?                                           17
9. How often do you practice aptitude questions?                                           17
10. Have you participated in any hackathons or coding competitions?                        17
11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?    17
12. Is your resume ready?                                                                  17
13. How confident are you in attending placement interviews?                               17
14. Which skill do you think you need to improve the most?                                 17
dtype: int64

In [15]:
# Fill missing values in numerical columns using mean
df['2.  Current CGPA']=df['2.  Current CGPA'].fillna(df['2.  Current CGPA'].mean())

In [16]:
df['4. How many hours do you practice coding per day?']=df['4. How many hours do you practice coding per day?'].fillna(df['4. How many hours do you practice coding per day?'].mode()[0])

In [17]:
df['7. How many certifications have you completed?'] = df['7. How many certifications have you completed?'].fillna(df['7. How many certifications have you completed?'].mode()[0])

In [18]:
df['13. How confident are you in attending placement interviews?'] = df['13. How confident are you in attending placement interviews?'].fillna(df['13. How confident are you in attending placement interviews?'].mean())

In [19]:
df.isnull().sum()

1. Year of Study                                                                           17
2.  Current CGPA                                                                            0
3. How many programming languages do you know?                                             17
4. How many hours do you practice coding per day?                                           0
5. How many academic or personal projects have you completed?                              17
6. Have you completed any internships?                                                     17
7. How many certifications have you completed?                                              0
8. How would you rate your communication skills?                                           17
9. How often do you practice aptitude questions?                                           17
10. Have you participated in any hackathons or coding competitions?                        17
11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?    17
12. Is your resume ready?                                                                  17
13. How confident are you in attending placement interviews?                                0
14. Which skill do you think you need to improve the most?                                 17
dtype: int64

In [20]:
df['1. Year of Study']=df['1. Year of Study'].fillna(df['1. Year of Study'].mode()[0])

In [21]:
df['3. How many programming languages do you know?'] = df['3. How many programming languages do you know?'].fillna(df['3. How many programming languages do you know?'].mode()[0])

In [22]:
df['5. How many academic or personal projects have you completed?'] = df['5. How many academic or personal projects have you completed?'].fillna(df['5. How many academic or personal projects have you completed?'].mode()[0])

In [23]:
df['6. Have you completed any internships?'] = df['6. Have you completed any internships?'].fillna(df['6. Have you completed any internships?'].mode()[0])

In [24]:
df['8. How would you rate your communication skills?'] = df['8. How would you rate your communication skills?'].fillna(df['8. How would you rate your communication skills?'].mode()[0])

In [25]:
df['9. How often do you practice aptitude questions?'] = df['9. How often do you practice aptitude questions?'].fillna(df['9. How often do you practice aptitude questions?'].mode()[0])

In [26]:
df['10. Have you participated in any hackathons or coding competitions?'] = df['10. Have you participated in any hackathons or coding competitions?'].fillna(df['10. Have you participated in any hackathons or coding competitions?'].mode()[0])

In [27]:
df['11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?'] = df['11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?'].fillna(df['11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?'].mode()[0])

In [28]:
df['12. Is your resume ready?'] = df['12. Is your resume ready?'].fillna(df['12. Is your resume ready?'].mode()[0])

In [29]:
df['14. Which skill do you think you need to improve the most?'] = df['14. Which skill do you think you need to improve the most?'].fillna(df['14. Which skill do you think you need to improve the most?'].mode()[0])

In [30]:
df.isnull().sum()

1. Year of Study                                                                           0
2.  Current CGPA                                                                           0
3. How many programming languages do you know?                                             0
4. How many hours do you practice coding per day?                                          0
5. How many academic or personal projects have you completed?                              0
6. Have you completed any internships?                                                     0
7. How many certifications have you completed?                                             0
8. How would you rate your communication skills?                                           0
9. How often do you practice aptitude questions?                                           0
10. Have you participated in any hackathons or coding competitions?                        0
11. Do you regularly practice coding on platforms like HackerRank,Leetcode or codechef?    0
12. Is your resume ready?                                                                  0
13. How confident are you in attending placement interviews?                               0
14. Which skill do you think you need to improve the most?                                 0
dtype: int64

In [31]:
#Checking duplicate values
df.duplicated().sum()

np.int64(34)

In [32]:
df=df.drop_duplicates()

In [33]:
df.duplicated().sum()

np.int64(0)